### PR TITLE
Use static by default. README, separate tests.

### PR DESCRIPTION
**Pull request by abelboldu**
* Updated READMEs
* Changed group_vars to fit the static setup by default.
* Added Vagrantfile.bgp to spin up which uses a "fake BGP" playbook.

### CODE REVIEW

**Comment by ryo-tagami** [comment]
@abelboldu Have you tested it on CentOS? I wonder if it works.

**Comment by ryo-tagami** [comment]
(with `vagrant up centos-7`, that is)

**Comment by abelboldu** [comment]
@ryo-tagami Tested on all distros. BGP functionality not fully tested yet, but ansible playbooks apply ok.

**Comment by ryo-tagami** [comment]
LGTM 👍

**Pull request merged**
